# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: banzaicloud/pvc-operator
  tag: 0.0.5
  pullPolicy: IfNotPresent

operator:
  watchedNamespace: ""
  ownerReferenceName: ""

nfs:
  namespace: ""
  serviceAccount:
    name: ""
    create: true

## Install Default RBAC roles and bindings
rbac:
  enabled: true
  psp:
    enabled: false

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
