# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: banzaicloud/pvc-operator
  tag: 0.0.4
  pullPolicy: IfNotPresent

operator:
  watchedNamespace: ""
  ownerReferenceName: ""

nfs:
  namespace: ""

## Install Default RBAC roles and bindings
rbac:
  enabled: true
  nfsServiceaccountName : "nfs-provisioner"
