apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodepool-labels-operator.fullname" . }}
  labels:
    app: {{ include "nodepool-labels-operator.name" . }}
    chart: {{ include "nodepool-labels-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nodepool-labels-operator.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ include "nodepool-labels-operator.name" . }}
        release: {{ .Release.Name }}
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nodepool-labels-operator.name" . }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "nodepool-labels-operator.fullname" . }}
      {{- if and .Values.rbac.enabled .Values.rbac.psp.enabled }}
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GIN_MODE
            value: release
          - name: NPLSO_CONTROLLER_NAMESPACE
            value: {{ .Release.Namespace }}
          ports:
            - name: healthcheck
              containerPort: {{ .Values.healthcheck.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.endpoint }}
              port: healthcheck
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.endpoint }}
              port: healthcheck
          volumeMounts:
          - name: config-volume
            mountPath: /config/
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
