# Default values for spot-termination-exporter
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

spotTerminationexporter:

  ## The official Banzai spot-termination-exporter image, change tag to use a different version.
  ## https://hub.docker.com/r/banzaicloud/spot-termination-exporter/tags/
  ##
  image:
    repository: "banzaicloud/spot-termination-exporter"
    tag: "0.0.1"

    ## Specify an imagePullPolicy (Required)
    ## It's recommended to change this to 'Always' if the image tag is 'latest'
    ## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
    imagePullPolicy: IfNotPresent

  replicas: 1

  service:
    ## Kubernetes service type
    type: ClusterIP

    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:

    ## Provide any additonal annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    # annotations:
  
  serviceMonitor:
    # enabled should be set to true to enable prometheus-operator discovery of this service
    enabled: true
    # additionalLabels is the set of additional labels to add to the ServiceMonitor
    additionalLabels: {}

  logLevel: "debug"

  # The address to listen on for HTTP requests.
  bindAddr: 9189
  hostPort: 9189

  # Metadata endpoint to query
  metadataEndpoint: "http://169.254.169.254/latest/meta-data/"

  # Path to metrics endpoint
  metricsPath: "/metrics"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 120m

useHostNetwork: true
nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}
  # runAsUser: 65534
