kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "logging-operator.fullname" . }}
  labels:
    app: {{ template "logging-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.toml: |-
    # This is the config for the logging operator

    [logging-operator]
    rbac = {{ .Values.rbac.enabled }}
    {{- if .Values.tls.enabled }}
    [tls]
    enabled = {{ .Values.tls.enabled }}
    secretName = "{{ .Values.tls.secretName }}"
    sharedKey = {{ derivePassword 1 "long" (.Release.Time | toString) .Release.Name .Chart.Name }}
    {{- end }}

    [fluent-bit]
    enabled = {{ .Values.fluentbit.enabled }}
    namespace = "{{ default .Release.Namespace .Values.fluentbit.namespace }}"

    [fluentd]
    enabled = {{ .Values.fluentd.enabled }}
    namespace = "{{  default .Release.Namespace .Values.fluentd.namespace }}"