apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "logging-operator.fullname" . }}
  labels:
    app: {{ template "logging-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "logging-operator.fullname" . }}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '{{ toJson .Values.tolerations }}'
      labels:
        name: {{ template "logging-operator.fullname" . }}
    spec:
      serviceAccountName: {{ template "logging-operator.fullname" . }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "logging-operator.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - logging-operator
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.watchNamespace}}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /logging-operator/config
          name: config
      volumes:
      - configMap:
          name: {{ template "logging-operator.fullname" . }}
        name: config
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
