apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "logging-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "logging-operator.name" . }}
    helm.sh/chart: {{ include "logging-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "logging-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: {{ toJson .Values.tolerations | quote }}
      labels:
        app.kubernetes.io/name: {{ include "logging-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "logging-operator.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
        - logging-operator
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.watchNamespace | quote }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ include "logging-operator.fullname" . | quote }}
        volumeMounts:
        - mountPath: /logging-operator/config
          name: config
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

    {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "logging-operator.fullname" . }}
    {{- else }}

      volumes:
      - configMap:
          name: {{ template "logging-operator.fullname" . }}
        name: config

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
