apiVersion: v1
appVersion: 0.60.1
description: Stripped down version of prometheus-operator to only provision the operator
  and nothing else
home: https://github.com/banzaicloud/banzai-charts
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- operator
- prometheus
name: prometheus-operator-standalone
version: 13.3.1
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/banzaicloud/banzai-charts
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
