# Default values for hollowtrees
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hollowtrees:

  ## The official Banzai hollowtrees image, change tag to use a different version.
  ## https://hub.docker.com/r/banzaicloud/hollowtrees/tags/
  ##
  image:
    repository: "banzaicloud/hollowtrees"
    tag: "0.0.1"

    ## Specify an imagePullPolicy (Required)
    ## It's recommended to change this to 'Always' if the image tag is 'latest'
    ## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
    imagePullPolicy: IfNotPresent

  replicas: 1

  service:
    ## Kubernetes service type
    type: ClusterIP

    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:

    ## Provide any additonal annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    # annotations:



  logLevel: "debug"
  logFormat: "text"
  
  # The address to listen on for HTTP requests. 
  bindAddr: 9092
  buffersize: 100


  rules:
      - name: "spot_to_drainer"
        description: "spot to k8s drainer"
        event_type: "prometheus.server.alert.SpotTerminationNotice"
        action_plugins:
            - "ht-k8s-action-plugin"
            - "ht-aws-asg-action-plugin"
        match:
            - cluster_name: "marton-cluster"

      - name: "spot_rebalance"
        description: "price alert to asg rebalance"
        event_type: "prometheus.server.alert.SpotInstanceTooExpensive"
        action_plugins:
            - "ht-aws-asg-action-plugin"
        match:
            - asg_name: "marci-test"


  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      memory: 256Mi
      cpu: 120m
