---
{{- if and .Values.queryFrontend.enabled .Values.queryFrontend.http.ingress.enabled }}
apiVersion: {{ .Values.queryFrontend.http.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: query-frontend
{{- if .Values.queryFrontend.http.ingress.labels }}
{{ toYaml .Values.queryFrontend.http.ingress.labels | indent 4 }}
{{- end }}
    {{- with .Values.queryFrontend.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.queryFrontend.http.ingress.defaultBackend }}
  backend:
    service:
      name: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
      port:
        number: {{ $.Values.queryFrontend.http.port }}
  {{- end }}
  {{- if .Values.queryFrontend.http.ingress.tls }}
  tls:
    {{- range .Values.queryFrontend.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.queryFrontend.http.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.queryFrontend.http.ingress.path }}
            pathType: {{ $.Values.queryFrontend.http.ingress.pathType }}
            backend:
              service:
                name: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
                port:
                  number: {{ $.Values.queryFrontend.http.port }}
  {{- end }}
{{- end }}

{{- if and .Values.queryFrontend.enabled .Values.queryFrontend.grpc.ingress.enabled }}
---
apiVersion: {{ .Values.queryFrontend.grpc.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "query-frontend") }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: query-frontend
{{- if .Values.queryFrontend.grpc.ingress.labels }}
{{ toYaml .Values.queryFrontend.grpc.ingress.labels | indent 4 }}
{{- end }}
    {{- with .Values.queryFrontend.grpc.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.queryFrontend.grpc.ingress.defaultBackend }}
  backend:
    service:
      name: {{ include "thanos.componentname" (list $ "query-frontend") }}-grpc
      port:
        number: {{ $.Values.queryFrontend.grpc.port }}
  {{- end }}
  {{- if .Values.queryFrontend.grpc.ingress.tls }}
  tls:
    {{- range .Values.queryFrontend.grpc.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.queryFrontend.grpc.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.queryFrontend.grpc.ingress.path }}
            pathType: {{ $.Values.queryFrontend.grpc.ingress.pathType }}
            backend:
              service:
                name: {{ include "thanos.componentname" (list $ "query-frontend") }}-grpc
                port:
                  number: {{ $.Values.queryFrontend.grpc.port }}
  {{- end }}
{{- end }}
