{{ if .Values.query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-query
  labels:
    app: {{ include "thanos.name" . }}-query
    chart: {{ include "thanos.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.query.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "thanos.name" . }}-query
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: {{ include "thanos.name" . }}-query
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        thanos-peer: "true"
      annotations:
      {{- with .Values.query.annotations }}
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.query.monitoring.enabled  }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.query.http.port}}"
      {{ end }}
    spec:
      containers:
      - name: thanos-query
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "query"
        - "--log.level={{ .Values.query.logLevel }}"
        - "--grpc-address=0.0.0.0:{{ .Values.query.grpc.port }}"
        - "--cluster.address={{ .Values.cluster.address }}:{{ .Values.cluster.port}}"
        - "--cluster.peers={{ include "thanos.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.cluster.port }}"
        - "--query.replica-label={{ .Values.replicaLabelName }}"
        - "--http-address=0.0.0.0:{{ .Values.query.http.port }}"
        {{- range $key, $value := .Values.query.extraArgs }}
        - --{{ $key }}{{ if $value }}={{ $value }}{{ end }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.query.http.port}}
        - name: grpc
          containerPort: {{ .Values.query.grpc.port }}
        - name: cluster
          containerPort: {{ .Values.cluster.port }}
        resources:
          {{ toYaml .Values.query.resources | nindent 10 }}
        {{- if .Values.query.certSecretName }}
        volumeMounts:
        - mountPath: /etc/certs
          name: {{ .Values.query.certSecretName }}
          readOnly: true
        {{- end }}
      securityContext:
        {{ toYaml .Values.query.securityContext | nindent 8 }}
      {{- if .Values.query.certSecretName }}
      volumes:
      - name: {{ .Values.query.certSecretName }}
        secret:
          defaultMode: 420
          secretName: {{ .Values.query.certSecretName }}
      {{- end }}
{{ end }}
