{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}
  labels:
    app: {{ include "thanos.name" . }}
    chart: {{ include "thanos.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cluster
    port: {{ .Values.cluster.port }}
    targetPort: cluster
  selector:
    thanos-peer: "true"
{{- end }}
