# S3 bucket endpoint URL exp: https://s3.amazonaws.com, https://s3.wasabisys.com, or http://minio-service.default.svc.cluster.local:9000
endpoint: ""

# S3 Bucket name exp: my-logging-01
bucketName: ""

# S3 bucket region
region: "us-west-1"

awsCredentialsAccess:
  enabled: false
  secret:
    # Kubernetes secret  name of amazon credentials.
    # Use existing secret, If empty it will be created.
    secretName: ""
    # Amazon Access Key Name
    awsAccessKey: AWS_ACCESS_KEY_ID
    # Amazon Access Key
    awsAccessValue: ""

    # Amazon Secret Key Name
    awsSecretKey: AWS_SECRET_ACCESS_KEY
    # Amazon Secret Key
    awsSecretValue: ""


assumeRoleCredentials:
  enabled: false
  secret:
    # Kubernetes secret  name of amazon credentials.
    # Use existing secret, If empty it will be created.
    secretName: ""

    # AssumeRole Key
    roleArnKey: ROLE_ARN
    # AssumeRole Value
    roleArnValue: ""

    # Role Session Key
    roleSessioNameKey: ROLE_SESSION_NAME
    # Role Session Value
    roleSessioNameValue: ""


instanceProfileCredentials:
  enabled: false
  ip_address: "169.254.169.254"
  port: "80"
