replicaCount: 1
logVerbosity: 1
apiService:
  group: admission.anchore.io
  version: v1beta1
image:
  repository: banzaicloud/anchore-image-validator
  tag: 0.3.3
  pullPolicy: IfNotPresent
service:
  name: anchoreimagecheck
  type: ClusterIP
  externalPort: 443
  internalPort: 8443
externalAnchore:
  anchoreHost: ""
  anchoreUser: ""
  anchorePass: ""
resources: {}

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

pspEnabled: false
