{{- range $service := (list "frontend" "history" "matching" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cadence.componentname" (list $ $service) }}
  labels:
    app.kubernetes.io/name: {{ include "cadence.name" $ }}
    helm.sh/chart: {{ include "cadence.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: {{ $service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  replicas: {{ default $.Values.server.replicaCount $serviceValues.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cadence.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cadence.name" $ }}
        helm.sh/chart: {{ include "cadence.chart" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: {{ $service }}
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmap.yaml") $ | sha256sum }}
        {{- if (default $.Values.server.metrics.annotations.enabled $serviceValues.metrics.annotations.enabled) }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        {{- end }}
        {{- with (default $.Values.server.podAnnotations $serviceValues.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml (default $.Values.server.podSecurityContext $serviceValues.podSecurityContext) | nindent 8 }}
      initContainers:
        {{- if $.Values.cassandra.enabled }}
        - name: check-cassandra-service
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ include "cassandra.host" $ }}; do echo waiting for cassandra service; sleep 1; done;']
        - name: check-cassandra
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: "{{ $.Values.cassandra.image.repo }}:{{ $.Values.cassandra.image.tag }}"
          imagePullPolicy: {{ $.Values.cassandra.image.pullPolicy }}
          command: ['sh', '-c', 'until cqlsh {{ include "cassandra.host" $ }} {{ $.Values.cassandra.config.ports.cql }} -e "SHOW VERSION"; do echo waiting for cassandra to start; sleep 1; done;']
        - name: check-cassandra-cadence-schema
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: "{{ $.Values.cassandra.image.repo }}:{{ $.Values.cassandra.image.tag }}"
          imagePullPolicy: {{ $.Values.cassandra.image.pullPolicy }}
          command: ['sh', '-c', 'until cqlsh {{ include "cassandra.host" $ }} {{ $.Values.cassandra.config.ports.cql }} -e "SELECT keyspace_name FROM system_schema.keyspaces" | grep {{ $.Values.server.config.persistence.default.cassandra.keyspace }}$; do echo waiting for default keyspace to become ready; sleep 1; done;']
        - name: check-cassandra-visibility-schema
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: "{{ $.Values.cassandra.image.repo }}:{{ $.Values.cassandra.image.tag }}"
          imagePullPolicy: {{ $.Values.cassandra.image.pullPolicy }}
          command: ['sh', '-c', 'until cqlsh {{ include "cassandra.host" $ }} {{ $.Values.cassandra.config.ports.cql }} -e "SELECT keyspace_name FROM system_schema.keyspaces" | grep {{ $.Values.server.config.persistence.visibility.cassandra.keyspace }}$; do echo waiting for visibility keyspace to become ready; sleep 1; done;']
        {{- else if $.Values.mysql.enabled  }}
        - name: check-mysql-service
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ include "mysql.host" $ }}; do echo waiting for mysql service; sleep 1; done;']
        - name: check-mysql-port
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: busybox
          command: ['sh', '-c', 'until echo STATUS | nc -w 2 {{ include "mysql.host" $ }} {{ $.Values.mysql.service.port }}; do echo waiting for mysql to start; sleep 1; done;']
        {{- else }}
          []
        {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $service }}
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: "{{ $.Values.server.image.repository }}:{{ $.Values.server.image.tag }}"
          imagePullPolicy: {{ $.Values.server.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICES
              value: {{ $service }}
            - name: CADENCE_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cadence.persistence.secretName" (list $ "default") }}
                  key: {{ include "cadence.persistence.secretKey" (list $ "default") }}
            - name: CADENCE_VISIBILITY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cadence.persistence.secretName" (list $ "visibility") }}
                  key: {{ include "cadence.persistence.secretKey" (list $ "visibility") }}
          ports:
            - name: rpc
              containerPort: {{ include (printf "cadence.%s.internalPort" $service) $ }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 150
            tcpSocket:
              port: rpc
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: rpc
          volumeMounts:
            - name: configMap
              mountPath: /etc/cadence/config_map/config_template.yaml
              subPath: config_template.yaml
            - name: configMap
              mountPath: /etc/cadence/config_map/dynamicconfig/config.yaml
              subPath: dynamic_config.yaml
            - name: config
              mountPath: /etc/cadence/config
          resources:
            {{- toYaml (default $.Values.server.resources $serviceValues.resources) | nindent 12 }}
      volumes:
        - name: configMap
          configMap:
            name: {{ include "cadence.fullname" $ }}
        - name: config
          emptyDir: {}
      {{- with (default $.Values.server.nodeSelector $serviceValues.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with (default $.Values.server.affinity $serviceValues.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with (default $.Values.server.tolerations $serviceValues.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
{{- end }}
