# Default values for spot-config-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
logVerbosity: 8

apiService:
  group: admission.banzaicloud.com
  version: v1beta1
  resource: spotscheduling

image:
  repository: banzaicloud/spot-config-webhook
  tag: 0.1.3
  pullPolicy: IfNotPresent

service:
  name: spotwebhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443

rbac:
  enabled: true
  psp:
    enabled: false

webhook:
  spotAnnotationKey: "app.banzaicloud.io/odPercentage"
  configMapNamespace: "pipeline-system"
  configMapName: "spot-deploy-config"
  schedulerName: "spot-scheduler"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
